name: OfflinePlayers
version: 3.6.1
authors:
  - snap20lp
  - Sugaku
api-version: 1.13
main: de.snap20lp.offlineplayers.OfflinePlayers

depend: [ "packetevents", "LibsDisguises" ]

softdepend:
  - "Towny"
  - "Multiverse-Inventories"
  - "WorldGuard"
  - "GravesX"
  - "AngelChest"

commands:
  offline-player:
    permission: offline-player.admin
    permission-message: "Unknown command. Please type \"help\" for help."
permissions:
  offline-player.*:
    default: op
    offline-player.admin:
      default: op
