name: OfflinePlayers
version: 3.3.3
authors:
  - snap20lp
  - Sugaku
api-version: 1.13
main: de.snap20lp.offlineplayers.OfflinePlayers

softdepend:
  - LibsDisguises
  - Towny
  - Multiverse-Inventories
  - DepartedDepot
  - WorldGuard
commands:
  offline-teleport:
    description: "Command to allow for easier teleportation to offline players."
    permission: "offline-players.teleport"
permissions:
  offline-players.*:
    default: op
    offline-players.admin:
      default: op
    offline-players.teleport:
      default: op
