name: OfflinePlayers
version: 3.5.2
authors:
  - snap20lp
  - Sugaku
api-version: 1.13
main: de.snap20lp.offlineplayers.OfflinePlayers

depend: [ "packetevents", "LibsDisguises" ]

softdepend:
  - "Towny"
  - "Multiverse-Inventories"
  - "DepartedDepot"
  - "WorldGuard"
  - "GravesX"
  - "AngelChest"
