name: OfflinePlayers
version: 3.1.1
authors:
  - snap20lp
  - Sugaku
api-version: 1.13
main: de.snap20lp.offlineplayers.OfflinePlayers

softdepend:
  - LibsDisguises
  - Towny
  - Multiverse-Inventories
